In [5]:
import numpy as np
from nptyping import NDArray ,Shape




# Dimensions of Array

In [6]:
# 3D array
arr:list[list[list[int]]] = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]


In [7]:
# 2D array
arr:list[list[int]] = [[1,2,3],[4,5,6]]
arr[1][1]

5

In [8]:
arr:NDArray= np.array(1000)
print(arr,"===",type(arr))
print(arr.shape,"Shape of array")
print(arr.dtype,"Data type of array")
print(arr.ndim,"Dimension of array")
print(arr.itemsize,"Size of each element in bytes")
print(arr.nbytes,"Total size of array in bytes")
print(arr.size,"Total number of elements in array")
print(arr.data,"Memory address of array")
print(arr.strides,"Strides of array")
print(arr.base,"Base of array")
print(arr.data.obj,"Object of array")
print(arr.flags,"Flags of array")

1000 === <class 'numpy.ndarray'>
() Shape of array
int32 Data type of array
0 Dimension of array
4 Size of each element in bytes
4 Total size of array in bytes
1 Total number of elements in array
<memory at 0x0000025038764400> Memory address of array
() Strides of array
None Base of array
1000 Object of array
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
 Flags of array


In [9]:
from typing import Any
from nptyping import NDArray ,Shape

arr:NDArray[Shape["10"],Any] = np.array([[1,2,3,4],[5,6,7,8]])
# print(arr,"===",type(arr))
# print(arr.shape,"Shape of array")
# print(arr.dtype,"Data type of array")
# print(arr.ndim,"Dimension of array")
# print(arr.itemsize,"Size of each element in bytes")
# print(arr.nbytes,"Total size of array in bytes")
# print(arr.size,"Total number of elements in array")
# print(arr.data,"Memory address of array")   
# print(arr.strides,"Strides of array")
# print(arr.base,"Base of array")
# print(arr.data.obj,"Object of array")
# print(arr.flags,"Flags of array")

In [10]:
from typing import Any
my_list:NDArray[Shape["2 , 4"],Any] = np.array([[1,2,3,4],[5,6,7,8]])
# my_list_range:NDArray[Shape["10"],Any] = np.arange(1,11)
# my_list_range.shape
# you can perform any operation on the elements of the array without using loop ot using list comprehension you can do ot directly.

# display(my_list_range + my_list_range)
display(my_list + my_list)


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [13]:
my_arr = np.array([1,2,3,4])
my_arr[0:3] = 100
my_arr


array([100, 100, 100,   4])

In [21]:
my_arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
my_arr[0:1,0:2]

array([[1, 2]])

In numpy you can also do boolean slicing

In [27]:
my_arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
new_arr = my_arr[0:1,0:2,0:4]
remainder = new_arr % 2 == 0
new_arr[remainder]

array([2, 4, 6, 8])

In [53]:
myarr = np.arange(1*1*3).reshape(1,1,3)
myarr

array([[[0, 1, 2]]])